//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHoKhau.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIET_PHANQUYEN
    {
        public string MaLoaiCongAn { get; set; }
        public string MaQuyen { get; set; }
        public string MoTa { get; set; }
    
        public virtual LOAICONGAN LOAICONGAN { get; set; }
        public virtual QUYEN QUYEN { get; set; }
    }
}
