//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHoKhau.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUDUYETCHUYENKHAU
    {
        public string MaPhieuThayDoi { get; set; }
        public string CMND { get; set; }
        public string MaSHKChuyenDen { get; set; }
        public string MaSoLuuChuyenKhau { get; set; }
        public string MaCongAn { get; set; }
        public string LyDo { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayDuyet { get; set; }
        public bool DaDuyet { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual CONGAN CONGAN { get; set; }
        public virtual NHANKHAU NHANKHAU { get; set; }
        public virtual SOHOKHAU SOHOKHAU { get; set; }
        public virtual SOLUUCHUYENKHAU SOLUUCHUYENKHAU { get; set; }
    }
}
