//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHoKhau.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUTHAYDOI_HK_NK
    {
        public string MaPhieuThayDoi { get; set; }
        public string CMND { get; set; }
        public string MaSoLuuChuyenKhau { get; set; }
        public string MaCongAn { get; set; }
        public System.DateTime NgayKhaiBao { get; set; }
        public string NoiThayDoi { get; set; }
        public string LyDo { get; set; }
    
        public virtual CONGAN CONGAN { get; set; }
        public virtual NHANKHAU NHANKHAU { get; set; }
        public virtual SOLUUCHUYENKHAU SOLUUCHUYENKHAU { get; set; }
    }
}
