//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHoKhau.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUDUYETSOHOKHAU
    {
        public string MaPD_SHK { get; set; }
        public string MaSHK_PendingInfo { get; set; }
        public string MaSHK { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayDuyet { get; set; }
        public string ActionType { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual SOHOKHAU SOHOKHAU { get; set; }
        public virtual SOHOKHAU SOHOKHAU1 { get; set; }
    }
}
