//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHoKhau.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUKHAIBAOTAMVANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUKHAIBAOTAMVANG()
        {
            this.GIAYTAMTRUs = new HashSet<GIAYTAMTRU>();
        }
    
        public string MaPhieuKhaiBao { get; set; }
        public string MaSoLuuTamVang { get; set; }
        public string MaCongAn { get; set; }
        public string MaNhanKhau { get; set; }
        public System.DateTime NgayKhaiBao { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public System.DateTime NgayKetThuc { get; set; }
        public string LyDo { get; set; }
        public Nullable<int> CoTreEmDiTheo { get; set; }
    
        public virtual CONGAN CONGAN { get; set; }
        public virtual NHANKHAU NHANKHAU { get; set; }
        public virtual SOLUUTAMVANG SOLUUTAMVANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIAYTAMTRU> GIAYTAMTRUs { get; set; }
    }
}
