//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHoKhau.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLHKEntities : DbContext
    {
        public QLHKEntities()
            : base("name=QLHKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHITIET_PHANQUYEN> CHITIET_PHANQUYEN { get; set; }
        public virtual DbSet<CONGAN> CONGANs { get; set; }
        public virtual DbSet<DIAPHUONG> DIAPHUONGs { get; set; }
        public virtual DbSet<GIAYTAMTRU> GIAYTAMTRUs { get; set; }
        public virtual DbSet<LOAICONGAN> LOAICONGANs { get; set; }
        public virtual DbSet<NGUOI> NGUOIs { get; set; }
        public virtual DbSet<NHANKHAU> NHANKHAUs { get; set; }
        public virtual DbSet<PHIEUDUYETCHUYENKHAU> PHIEUDUYETCHUYENKHAUs { get; set; }
        public virtual DbSet<PHIEUDUYETNHANKHAU> PHIEUDUYETNHANKHAUs { get; set; }
        public virtual DbSet<PHIEUDUYETSOHOKHAU> PHIEUDUYETSOHOKHAUs { get; set; }
        public virtual DbSet<PHIEUKHAIBAOTAMVANG> PHIEUKHAIBAOTAMVANGs { get; set; }
        public virtual DbSet<QUYEN> QUYENs { get; set; }
        public virtual DbSet<SOHOKHAU> SOHOKHAUs { get; set; }
        public virtual DbSet<SOLUUCHUYENKHAU> SOLUUCHUYENKHAUs { get; set; }
        public virtual DbSet<SOLUUNHANKHAU> SOLUUNHANKHAUs { get; set; }
        public virtual DbSet<SOLUUTAMTRU> SOLUUTAMTRUs { get; set; }
        public virtual DbSet<SOLUUTAMVANG> SOLUUTAMVANGs { get; set; }
        public virtual DbSet<THAMSO> THAMSOes { get; set; }
    }
}
