//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHoKhau.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOHOKHAUCHODUYET
    {
        public string MaSHK { get; set; }
        public string CMNDChuHo { get; set; }
        public string MaCongAn { get; set; }
        public string MaSoLuuNhanKhau { get; set; }
        public string DiaChi { get; set; }
        public System.DateTime NgayTaoSo { get; set; }
        public string ActionType { get; set; }
    
        public virtual CONGAN CONGAN { get; set; }
        public virtual NHANKHAU NHANKHAU { get; set; }
        public virtual SOHOKHAU SOHOKHAU { get; set; }
        public virtual SOLUUNHANKHAU SOLUUNHANKHAU { get; set; }
    }
}
